Fri Jun 20 06:56:41 PM EDT 2025: Job 7353 is allocated resources.
Inside slurm_launcher.slrm (/cm/local/apps/slurm/var/spool/job07353/slurm_script). received arguments: playground/equiformer_eigen_dataset.py
Submitting /project/aip-aspuru/aburger/gad-ff/playground/equiformer_eigen_dataset.py
Traceback (most recent call last):
  File "/project/aip-aspuru/aburger/gad-ff/playground/equiformer_eigen_dataset.py", line 20, in <module>
    import torch
  File "/project/aip-aspuru/aburger/miniforge3/envs/gad/lib/python3.11/site-packages/torch/__init__.py", line 289, in <module>
    _load_global_deps()
  File "/project/aip-aspuru/aburger/miniforge3/envs/gad/lib/python3.11/site-packages/torch/__init__.py", line 245, in _load_global_deps
    raise err
  File "/project/aip-aspuru/aburger/miniforge3/envs/gad/lib/python3.11/site-packages/torch/__init__.py", line 226, in _load_global_deps
    ctypes.CDLL(global_deps_lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/project/aip-aspuru/aburger/miniforge3/envs/gad/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: libze_loader.so.1: cannot open shared object file: No such file or directory
